### PR TITLE
Obtain a reference to AbstractProject in validation.

### LINKED ISSUE #10: "Requirement files" field claims "File xx does not yet exist"
There's a yellow warning text under the field with that text, regardless of whether the file actually exists or not. Maybe it's related to my earlier problem (#8), but fortunately it does not interfere with the actual working of the plugin. It's only annoying.

### PR DESCRIPTION
**Pull request by kodekarl**
This enables us to look for the file(s) in "some workspace" instead of "somewhere".

This fixes #10 for me.

### CODE REVIEW

**Comment by kodekarl** [comment]
Bump?

**Comment by rmohr** [comment]
LGTM

**Comment by rmohr** [comment]
@kodekarl thank you.
Could you squash it into one commit?

**Comment by kodekarl** [comment]
Welcome back, @rmohr :-)
Sure, one squashed commit coming up.

**Pull request closed without merging**
